name: CI

on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-jammy
    continue-on-error: true
    strategy:
      matrix:
        dist: [ubuntu2204, fedora37]
        arch: [arm64, s390x, ppc64el]

    steps:
      - uses: actions/checkout@v3
      - name: Prepare cloud image build env
        run: |
          sudo apt update
          sudo apt install -y vagrant
      - name: Fetch ${{ matrix.dist }} ${{ matrix.arch }} cloud image
        run: ./fetch_img.sh ${{ matrix.dist }} ${{ matrix.arch }}
      - name: Convert ${{ matrix.dist }} ${{ matrix.arch }} cloud image to box
        run: |
          DIST=${{ matrix.dist }}
          case "$DIST" in
          ubuntu2204)
            RESOLVER=guestfish
            sudo apt install -y vagrant libguestfs-tools
            sudo chmod +r /boot/vmlinuz-*
            ;;
          fedora37)
            RESOLVER=cloud-init
            sudo apt install -y genisoimage qemu-system-arm qemu-system-ppc qemu-system-s390x qemu-system-misc qemu-efi opensbi u-boot-qemu
            ;;
          *)
            echo "Unsupported distro"
            exit 1
            ;;
          esac

          ./run.sh $RESOLVER ${{ matrix.arch }} base.img ${{ matrix.dist }}-${{ matrix.arch }}.box
      - name: Upload ${{ matrix.dist }} ${{ matrix.arch }} box
        run: |
          VERSION=$(date +'%y%m%d')
          vagrant cloud auth login -t ${{ secrets.VAGRANT_TOKEN }}
          vagrant cloud publish YMWR/${{ matrix.dist }}-${{ matrix.arch }} $VERSION libvirt ${{ matrix.dist }}-${{ matrix.arch }}.box -f -r
